apiVersion: v1
kind: Service
metadata:
  name: {{ include "smtp-to-sns-chart.fullname" . }}
  labels:
    {{- include "smtp-to-sns-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "smtp-to-sns-chart.selectorLabels" . | nindent 4 }}
